# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
# highlighter: pygments
markdown: kramdown
# disqus: dbyll
# google_analytics: dbyll
title: Caroline Salib

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Caroline Salib

description: Stylish Jekyll Theme
author:
  name: Caroline
  email: carolinesalibc@gmail.com
  github: carolinesalib
  twitter: carolinesalib_
  linkedin: carolinesalib
  bio: I'm a web developer, passionate about code quality, automated testing, open source projects and learn new things. I love to spend my time reading books, studying and being in nature. I like doing things the right way, and I am motived with new challenges.
  email_md5: 5ace742040f2337b77edc43884e0f070

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
